# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mahdi/codes/ftp-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mahdi/codes/ftp-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.23.0-rc5-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahdi/codes/ftp-server/CMakeFiles /home/mahdi/codes/ftp-server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahdi/codes/ftp-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ftp_server

# Build rule for target.
ftp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ftp_server
.PHONY : ftp_server

# fast build rule for target.
ftp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/build
.PHONY : ftp_server/fast

src/domain/directory/models/Directory.o: src/domain/directory/models/Directory.cpp.o
.PHONY : src/domain/directory/models/Directory.o

# target to build an object file
src/domain/directory/models/Directory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/directory/models/Directory.cpp.o
.PHONY : src/domain/directory/models/Directory.cpp.o

src/domain/directory/models/Directory.i: src/domain/directory/models/Directory.cpp.i
.PHONY : src/domain/directory/models/Directory.i

# target to preprocess a source file
src/domain/directory/models/Directory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/directory/models/Directory.cpp.i
.PHONY : src/domain/directory/models/Directory.cpp.i

src/domain/directory/models/Directory.s: src/domain/directory/models/Directory.cpp.s
.PHONY : src/domain/directory/models/Directory.s

# target to generate assembly for a file
src/domain/directory/models/Directory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/directory/models/Directory.cpp.s
.PHONY : src/domain/directory/models/Directory.cpp.s

src/domain/file/models/GrantedFile.o: src/domain/file/models/GrantedFile.cpp.o
.PHONY : src/domain/file/models/GrantedFile.o

# target to build an object file
src/domain/file/models/GrantedFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/models/GrantedFile.cpp.o
.PHONY : src/domain/file/models/GrantedFile.cpp.o

src/domain/file/models/GrantedFile.i: src/domain/file/models/GrantedFile.cpp.i
.PHONY : src/domain/file/models/GrantedFile.i

# target to preprocess a source file
src/domain/file/models/GrantedFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/models/GrantedFile.cpp.i
.PHONY : src/domain/file/models/GrantedFile.cpp.i

src/domain/file/models/GrantedFile.s: src/domain/file/models/GrantedFile.cpp.s
.PHONY : src/domain/file/models/GrantedFile.s

# target to generate assembly for a file
src/domain/file/models/GrantedFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/models/GrantedFile.cpp.s
.PHONY : src/domain/file/models/GrantedFile.cpp.s

src/domain/file/repositories/GrantedFileRepository.o: src/domain/file/repositories/GrantedFileRepository.cpp.o
.PHONY : src/domain/file/repositories/GrantedFileRepository.o

# target to build an object file
src/domain/file/repositories/GrantedFileRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/repositories/GrantedFileRepository.cpp.o
.PHONY : src/domain/file/repositories/GrantedFileRepository.cpp.o

src/domain/file/repositories/GrantedFileRepository.i: src/domain/file/repositories/GrantedFileRepository.cpp.i
.PHONY : src/domain/file/repositories/GrantedFileRepository.i

# target to preprocess a source file
src/domain/file/repositories/GrantedFileRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/repositories/GrantedFileRepository.cpp.i
.PHONY : src/domain/file/repositories/GrantedFileRepository.cpp.i

src/domain/file/repositories/GrantedFileRepository.s: src/domain/file/repositories/GrantedFileRepository.cpp.s
.PHONY : src/domain/file/repositories/GrantedFileRepository.s

# target to generate assembly for a file
src/domain/file/repositories/GrantedFileRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/repositories/GrantedFileRepository.cpp.s
.PHONY : src/domain/file/repositories/GrantedFileRepository.cpp.s

src/domain/file/services/GrantedFileService.o: src/domain/file/services/GrantedFileService.cpp.o
.PHONY : src/domain/file/services/GrantedFileService.o

# target to build an object file
src/domain/file/services/GrantedFileService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/services/GrantedFileService.cpp.o
.PHONY : src/domain/file/services/GrantedFileService.cpp.o

src/domain/file/services/GrantedFileService.i: src/domain/file/services/GrantedFileService.cpp.i
.PHONY : src/domain/file/services/GrantedFileService.i

# target to preprocess a source file
src/domain/file/services/GrantedFileService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/services/GrantedFileService.cpp.i
.PHONY : src/domain/file/services/GrantedFileService.cpp.i

src/domain/file/services/GrantedFileService.s: src/domain/file/services/GrantedFileService.cpp.s
.PHONY : src/domain/file/services/GrantedFileService.s

# target to generate assembly for a file
src/domain/file/services/GrantedFileService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/file/services/GrantedFileService.cpp.s
.PHONY : src/domain/file/services/GrantedFileService.cpp.s

src/domain/user/models/User.o: src/domain/user/models/User.cpp.o
.PHONY : src/domain/user/models/User.o

# target to build an object file
src/domain/user/models/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/models/User.cpp.o
.PHONY : src/domain/user/models/User.cpp.o

src/domain/user/models/User.i: src/domain/user/models/User.cpp.i
.PHONY : src/domain/user/models/User.i

# target to preprocess a source file
src/domain/user/models/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/models/User.cpp.i
.PHONY : src/domain/user/models/User.cpp.i

src/domain/user/models/User.s: src/domain/user/models/User.cpp.s
.PHONY : src/domain/user/models/User.s

# target to generate assembly for a file
src/domain/user/models/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/models/User.cpp.s
.PHONY : src/domain/user/models/User.cpp.s

src/domain/user/repositories/UserRepository.o: src/domain/user/repositories/UserRepository.cpp.o
.PHONY : src/domain/user/repositories/UserRepository.o

# target to build an object file
src/domain/user/repositories/UserRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/repositories/UserRepository.cpp.o
.PHONY : src/domain/user/repositories/UserRepository.cpp.o

src/domain/user/repositories/UserRepository.i: src/domain/user/repositories/UserRepository.cpp.i
.PHONY : src/domain/user/repositories/UserRepository.i

# target to preprocess a source file
src/domain/user/repositories/UserRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/repositories/UserRepository.cpp.i
.PHONY : src/domain/user/repositories/UserRepository.cpp.i

src/domain/user/repositories/UserRepository.s: src/domain/user/repositories/UserRepository.cpp.s
.PHONY : src/domain/user/repositories/UserRepository.s

# target to generate assembly for a file
src/domain/user/repositories/UserRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/repositories/UserRepository.cpp.s
.PHONY : src/domain/user/repositories/UserRepository.cpp.s

src/domain/user/services/UserService.o: src/domain/user/services/UserService.cpp.o
.PHONY : src/domain/user/services/UserService.o

# target to build an object file
src/domain/user/services/UserService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/services/UserService.cpp.o
.PHONY : src/domain/user/services/UserService.cpp.o

src/domain/user/services/UserService.i: src/domain/user/services/UserService.cpp.i
.PHONY : src/domain/user/services/UserService.i

# target to preprocess a source file
src/domain/user/services/UserService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/services/UserService.cpp.i
.PHONY : src/domain/user/services/UserService.cpp.i

src/domain/user/services/UserService.s: src/domain/user/services/UserService.cpp.s
.PHONY : src/domain/user/services/UserService.s

# target to generate assembly for a file
src/domain/user/services/UserService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/domain/user/services/UserService.cpp.s
.PHONY : src/domain/user/services/UserService.cpp.s

src/framework/handler/AuthenticationHandler.o: src/framework/handler/AuthenticationHandler.cpp.o
.PHONY : src/framework/handler/AuthenticationHandler.o

# target to build an object file
src/framework/handler/AuthenticationHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/AuthenticationHandler.cpp.o
.PHONY : src/framework/handler/AuthenticationHandler.cpp.o

src/framework/handler/AuthenticationHandler.i: src/framework/handler/AuthenticationHandler.cpp.i
.PHONY : src/framework/handler/AuthenticationHandler.i

# target to preprocess a source file
src/framework/handler/AuthenticationHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/AuthenticationHandler.cpp.i
.PHONY : src/framework/handler/AuthenticationHandler.cpp.i

src/framework/handler/AuthenticationHandler.s: src/framework/handler/AuthenticationHandler.cpp.s
.PHONY : src/framework/handler/AuthenticationHandler.s

# target to generate assembly for a file
src/framework/handler/AuthenticationHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/AuthenticationHandler.cpp.s
.PHONY : src/framework/handler/AuthenticationHandler.cpp.s

src/framework/handler/CommonHandler.o: src/framework/handler/CommonHandler.cpp.o
.PHONY : src/framework/handler/CommonHandler.o

# target to build an object file
src/framework/handler/CommonHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/CommonHandler.cpp.o
.PHONY : src/framework/handler/CommonHandler.cpp.o

src/framework/handler/CommonHandler.i: src/framework/handler/CommonHandler.cpp.i
.PHONY : src/framework/handler/CommonHandler.i

# target to preprocess a source file
src/framework/handler/CommonHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/CommonHandler.cpp.i
.PHONY : src/framework/handler/CommonHandler.cpp.i

src/framework/handler/CommonHandler.s: src/framework/handler/CommonHandler.cpp.s
.PHONY : src/framework/handler/CommonHandler.s

# target to generate assembly for a file
src/framework/handler/CommonHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/CommonHandler.cpp.s
.PHONY : src/framework/handler/CommonHandler.cpp.s

src/framework/handler/FileHandler.o: src/framework/handler/FileHandler.cpp.o
.PHONY : src/framework/handler/FileHandler.o

# target to build an object file
src/framework/handler/FileHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/FileHandler.cpp.o
.PHONY : src/framework/handler/FileHandler.cpp.o

src/framework/handler/FileHandler.i: src/framework/handler/FileHandler.cpp.i
.PHONY : src/framework/handler/FileHandler.i

# target to preprocess a source file
src/framework/handler/FileHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/FileHandler.cpp.i
.PHONY : src/framework/handler/FileHandler.cpp.i

src/framework/handler/FileHandler.s: src/framework/handler/FileHandler.cpp.s
.PHONY : src/framework/handler/FileHandler.s

# target to generate assembly for a file
src/framework/handler/FileHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/FileHandler.cpp.s
.PHONY : src/framework/handler/FileHandler.cpp.s

src/framework/handler/Handler.o: src/framework/handler/Handler.cpp.o
.PHONY : src/framework/handler/Handler.o

# target to build an object file
src/framework/handler/Handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/Handler.cpp.o
.PHONY : src/framework/handler/Handler.cpp.o

src/framework/handler/Handler.i: src/framework/handler/Handler.cpp.i
.PHONY : src/framework/handler/Handler.i

# target to preprocess a source file
src/framework/handler/Handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/Handler.cpp.i
.PHONY : src/framework/handler/Handler.cpp.i

src/framework/handler/Handler.s: src/framework/handler/Handler.cpp.s
.PHONY : src/framework/handler/Handler.s

# target to generate assembly for a file
src/framework/handler/Handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/handler/Handler.cpp.s
.PHONY : src/framework/handler/Handler.cpp.s

src/framework/router/Router.o: src/framework/router/Router.cpp.o
.PHONY : src/framework/router/Router.o

# target to build an object file
src/framework/router/Router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/router/Router.cpp.o
.PHONY : src/framework/router/Router.cpp.o

src/framework/router/Router.i: src/framework/router/Router.cpp.i
.PHONY : src/framework/router/Router.i

# target to preprocess a source file
src/framework/router/Router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/router/Router.cpp.i
.PHONY : src/framework/router/Router.cpp.i

src/framework/router/Router.s: src/framework/router/Router.cpp.s
.PHONY : src/framework/router/Router.s

# target to generate assembly for a file
src/framework/router/Router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/framework/router/Router.cpp.s
.PHONY : src/framework/router/Router.cpp.s

src/infrastructure/BaseEntity.o: src/infrastructure/BaseEntity.cpp.o
.PHONY : src/infrastructure/BaseEntity.o

# target to build an object file
src/infrastructure/BaseEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/BaseEntity.cpp.o
.PHONY : src/infrastructure/BaseEntity.cpp.o

src/infrastructure/BaseEntity.i: src/infrastructure/BaseEntity.cpp.i
.PHONY : src/infrastructure/BaseEntity.i

# target to preprocess a source file
src/infrastructure/BaseEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/BaseEntity.cpp.i
.PHONY : src/infrastructure/BaseEntity.cpp.i

src/infrastructure/BaseEntity.s: src/infrastructure/BaseEntity.cpp.s
.PHONY : src/infrastructure/BaseEntity.s

# target to generate assembly for a file
src/infrastructure/BaseEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/BaseEntity.cpp.s
.PHONY : src/infrastructure/BaseEntity.cpp.s

src/infrastructure/config/ServerConfig.o: src/infrastructure/config/ServerConfig.cpp.o
.PHONY : src/infrastructure/config/ServerConfig.o

# target to build an object file
src/infrastructure/config/ServerConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/config/ServerConfig.cpp.o
.PHONY : src/infrastructure/config/ServerConfig.cpp.o

src/infrastructure/config/ServerConfig.i: src/infrastructure/config/ServerConfig.cpp.i
.PHONY : src/infrastructure/config/ServerConfig.i

# target to preprocess a source file
src/infrastructure/config/ServerConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/config/ServerConfig.cpp.i
.PHONY : src/infrastructure/config/ServerConfig.cpp.i

src/infrastructure/config/ServerConfig.s: src/infrastructure/config/ServerConfig.cpp.s
.PHONY : src/infrastructure/config/ServerConfig.s

# target to generate assembly for a file
src/infrastructure/config/ServerConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/config/ServerConfig.cpp.s
.PHONY : src/infrastructure/config/ServerConfig.cpp.s

src/infrastructure/logger/Logger.o: src/infrastructure/logger/Logger.cpp.o
.PHONY : src/infrastructure/logger/Logger.o

# target to build an object file
src/infrastructure/logger/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/Logger.cpp.o
.PHONY : src/infrastructure/logger/Logger.cpp.o

src/infrastructure/logger/Logger.i: src/infrastructure/logger/Logger.cpp.i
.PHONY : src/infrastructure/logger/Logger.i

# target to preprocess a source file
src/infrastructure/logger/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/Logger.cpp.i
.PHONY : src/infrastructure/logger/Logger.cpp.i

src/infrastructure/logger/Logger.s: src/infrastructure/logger/Logger.cpp.s
.PHONY : src/infrastructure/logger/Logger.s

# target to generate assembly for a file
src/infrastructure/logger/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/Logger.cpp.s
.PHONY : src/infrastructure/logger/Logger.cpp.s

src/infrastructure/logger/LoggerFactory.o: src/infrastructure/logger/LoggerFactory.cpp.o
.PHONY : src/infrastructure/logger/LoggerFactory.o

# target to build an object file
src/infrastructure/logger/LoggerFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/LoggerFactory.cpp.o
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.o

src/infrastructure/logger/LoggerFactory.i: src/infrastructure/logger/LoggerFactory.cpp.i
.PHONY : src/infrastructure/logger/LoggerFactory.i

# target to preprocess a source file
src/infrastructure/logger/LoggerFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/LoggerFactory.cpp.i
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.i

src/infrastructure/logger/LoggerFactory.s: src/infrastructure/logger/LoggerFactory.cpp.s
.PHONY : src/infrastructure/logger/LoggerFactory.s

# target to generate assembly for a file
src/infrastructure/logger/LoggerFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/logger/LoggerFactory.cpp.s
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.s

src/infrastructure/repository/Repository.o: src/infrastructure/repository/Repository.cpp.o
.PHONY : src/infrastructure/repository/Repository.o

# target to build an object file
src/infrastructure/repository/Repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/repository/Repository.cpp.o
.PHONY : src/infrastructure/repository/Repository.cpp.o

src/infrastructure/repository/Repository.i: src/infrastructure/repository/Repository.cpp.i
.PHONY : src/infrastructure/repository/Repository.i

# target to preprocess a source file
src/infrastructure/repository/Repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/repository/Repository.cpp.i
.PHONY : src/infrastructure/repository/Repository.cpp.i

src/infrastructure/repository/Repository.s: src/infrastructure/repository/Repository.cpp.s
.PHONY : src/infrastructure/repository/Repository.s

# target to generate assembly for a file
src/infrastructure/repository/Repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/repository/Repository.cpp.s
.PHONY : src/infrastructure/repository/Repository.cpp.s

src/infrastructure/server/Server.o: src/infrastructure/server/Server.cpp.o
.PHONY : src/infrastructure/server/Server.o

# target to build an object file
src/infrastructure/server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/server/Server.cpp.o
.PHONY : src/infrastructure/server/Server.cpp.o

src/infrastructure/server/Server.i: src/infrastructure/server/Server.cpp.i
.PHONY : src/infrastructure/server/Server.i

# target to preprocess a source file
src/infrastructure/server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/server/Server.cpp.i
.PHONY : src/infrastructure/server/Server.cpp.i

src/infrastructure/server/Server.s: src/infrastructure/server/Server.cpp.s
.PHONY : src/infrastructure/server/Server.s

# target to generate assembly for a file
src/infrastructure/server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/server/Server.cpp.s
.PHONY : src/infrastructure/server/Server.cpp.s

src/infrastructure/socket/WebSocket.o: src/infrastructure/socket/WebSocket.cpp.o
.PHONY : src/infrastructure/socket/WebSocket.o

# target to build an object file
src/infrastructure/socket/WebSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/socket/WebSocket.cpp.o
.PHONY : src/infrastructure/socket/WebSocket.cpp.o

src/infrastructure/socket/WebSocket.i: src/infrastructure/socket/WebSocket.cpp.i
.PHONY : src/infrastructure/socket/WebSocket.i

# target to preprocess a source file
src/infrastructure/socket/WebSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/socket/WebSocket.cpp.i
.PHONY : src/infrastructure/socket/WebSocket.cpp.i

src/infrastructure/socket/WebSocket.s: src/infrastructure/socket/WebSocket.cpp.s
.PHONY : src/infrastructure/socket/WebSocket.s

# target to generate assembly for a file
src/infrastructure/socket/WebSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/socket/WebSocket.cpp.s
.PHONY : src/infrastructure/socket/WebSocket.cpp.s

src/infrastructure/time/TimeService.o: src/infrastructure/time/TimeService.cpp.o
.PHONY : src/infrastructure/time/TimeService.o

# target to build an object file
src/infrastructure/time/TimeService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/time/TimeService.cpp.o
.PHONY : src/infrastructure/time/TimeService.cpp.o

src/infrastructure/time/TimeService.i: src/infrastructure/time/TimeService.cpp.i
.PHONY : src/infrastructure/time/TimeService.i

# target to preprocess a source file
src/infrastructure/time/TimeService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/time/TimeService.cpp.i
.PHONY : src/infrastructure/time/TimeService.cpp.i

src/infrastructure/time/TimeService.s: src/infrastructure/time/TimeService.cpp.s
.PHONY : src/infrastructure/time/TimeService.s

# target to generate assembly for a file
src/infrastructure/time/TimeService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/time/TimeService.cpp.s
.PHONY : src/infrastructure/time/TimeService.cpp.s

src/infrastructure/workContext/WorkContext.o: src/infrastructure/workContext/WorkContext.cpp.o
.PHONY : src/infrastructure/workContext/WorkContext.o

# target to build an object file
src/infrastructure/workContext/WorkContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/workContext/WorkContext.cpp.o
.PHONY : src/infrastructure/workContext/WorkContext.cpp.o

src/infrastructure/workContext/WorkContext.i: src/infrastructure/workContext/WorkContext.cpp.i
.PHONY : src/infrastructure/workContext/WorkContext.i

# target to preprocess a source file
src/infrastructure/workContext/WorkContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/workContext/WorkContext.cpp.i
.PHONY : src/infrastructure/workContext/WorkContext.cpp.i

src/infrastructure/workContext/WorkContext.s: src/infrastructure/workContext/WorkContext.cpp.s
.PHONY : src/infrastructure/workContext/WorkContext.s

# target to generate assembly for a file
src/infrastructure/workContext/WorkContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/infrastructure/workContext/WorkContext.cpp.s
.PHONY : src/infrastructure/workContext/WorkContext.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ftp_server.dir/build.make CMakeFiles/ftp_server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ftp_server"
	@echo "... src/domain/directory/models/Directory.o"
	@echo "... src/domain/directory/models/Directory.i"
	@echo "... src/domain/directory/models/Directory.s"
	@echo "... src/domain/file/models/GrantedFile.o"
	@echo "... src/domain/file/models/GrantedFile.i"
	@echo "... src/domain/file/models/GrantedFile.s"
	@echo "... src/domain/file/repositories/GrantedFileRepository.o"
	@echo "... src/domain/file/repositories/GrantedFileRepository.i"
	@echo "... src/domain/file/repositories/GrantedFileRepository.s"
	@echo "... src/domain/file/services/GrantedFileService.o"
	@echo "... src/domain/file/services/GrantedFileService.i"
	@echo "... src/domain/file/services/GrantedFileService.s"
	@echo "... src/domain/user/models/User.o"
	@echo "... src/domain/user/models/User.i"
	@echo "... src/domain/user/models/User.s"
	@echo "... src/domain/user/repositories/UserRepository.o"
	@echo "... src/domain/user/repositories/UserRepository.i"
	@echo "... src/domain/user/repositories/UserRepository.s"
	@echo "... src/domain/user/services/UserService.o"
	@echo "... src/domain/user/services/UserService.i"
	@echo "... src/domain/user/services/UserService.s"
	@echo "... src/framework/handler/AuthenticationHandler.o"
	@echo "... src/framework/handler/AuthenticationHandler.i"
	@echo "... src/framework/handler/AuthenticationHandler.s"
	@echo "... src/framework/handler/CommonHandler.o"
	@echo "... src/framework/handler/CommonHandler.i"
	@echo "... src/framework/handler/CommonHandler.s"
	@echo "... src/framework/handler/FileHandler.o"
	@echo "... src/framework/handler/FileHandler.i"
	@echo "... src/framework/handler/FileHandler.s"
	@echo "... src/framework/handler/Handler.o"
	@echo "... src/framework/handler/Handler.i"
	@echo "... src/framework/handler/Handler.s"
	@echo "... src/framework/router/Router.o"
	@echo "... src/framework/router/Router.i"
	@echo "... src/framework/router/Router.s"
	@echo "... src/infrastructure/BaseEntity.o"
	@echo "... src/infrastructure/BaseEntity.i"
	@echo "... src/infrastructure/BaseEntity.s"
	@echo "... src/infrastructure/config/ServerConfig.o"
	@echo "... src/infrastructure/config/ServerConfig.i"
	@echo "... src/infrastructure/config/ServerConfig.s"
	@echo "... src/infrastructure/logger/Logger.o"
	@echo "... src/infrastructure/logger/Logger.i"
	@echo "... src/infrastructure/logger/Logger.s"
	@echo "... src/infrastructure/logger/LoggerFactory.o"
	@echo "... src/infrastructure/logger/LoggerFactory.i"
	@echo "... src/infrastructure/logger/LoggerFactory.s"
	@echo "... src/infrastructure/repository/Repository.o"
	@echo "... src/infrastructure/repository/Repository.i"
	@echo "... src/infrastructure/repository/Repository.s"
	@echo "... src/infrastructure/server/Server.o"
	@echo "... src/infrastructure/server/Server.i"
	@echo "... src/infrastructure/server/Server.s"
	@echo "... src/infrastructure/socket/WebSocket.o"
	@echo "... src/infrastructure/socket/WebSocket.i"
	@echo "... src/infrastructure/socket/WebSocket.s"
	@echo "... src/infrastructure/time/TimeService.o"
	@echo "... src/infrastructure/time/TimeService.i"
	@echo "... src/infrastructure/time/TimeService.s"
	@echo "... src/infrastructure/workContext/WorkContext.o"
	@echo "... src/infrastructure/workContext/WorkContext.i"
	@echo "... src/infrastructure/workContext/WorkContext.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

